title: Standard for Public Code
version: 0.1.1

remote_theme: publiccodenet/jekyll-theme
include:
  - "README.md"
  - "CONTRIBUTING.md"
  - "LICENSE.md"
  - "CODE_OF_CONDUCT.md"

toc: true

defaults:
  -
    scope:
      path: '/codebase-criteria/[!index]*'
    values:
      breadcrumbs:
        - name: 'Codebase criteria'
          path: '/codebase-criteria/'
  -
    scope:
      path: '/community-criteria/[!index]*'
    values:
      breadcrumbs:
        - name: 'Community criteria'
          path: '/community-criteria/'
  -
    scope:
      path: '/'
    values:
      breadcrumbs: true
