remote_theme: publiccodenet/jekyll-theme
title: Standard for Public Code

include: 
  - "README.md"
  - "CONTRIBUTING.md"
  - "license.md"
  - "CODE_OF_CONDUCT.md"

toc: true

defaults:
  -
    scope:
      path: '/criteria/[!index]*'
    values:
      breadcrumbs:
        - name: 'Criteria'
          path: '/criteria/'
  -
    scope: 
      path: '/'
    values:
      breadcrumbs: true
