title: Standard for Public Code
version: 0.2.0

remote_theme: publiccodenet/jekyll-theme
include:
  - "README.md"
  - "CONTRIBUTING.md"
  - "LICENSE.md"
  - "CODE_OF_CONDUCT.md"

toc: true

defaults:
  -
    scope:
      path: '/criteria/[!index]*'
    values:
      breadcrumbs:
        - name: 'Criteria'
          path: '/criteria/'
  -
    scope:
      path: '/'
    values:
      breadcrumbs: true
